name: Daily AI Vibe Check

on:
  schedule:
    - cron: '0 */8 * * *' # Run every 8 hours
  workflow_dispatch: # Allows you to click a button to run it manually

permissions:
  contents: write

jobs:
  update-vibe:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Vibe Check
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        run: python main.py

      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add vibe.svg
          git commit -m "Update Daily Vibe Check" || exit 0
          git push
